### ISSUE TITLE
Resource kind abbreviations are less clear than just using actual resource name

### ISSUE THREAD

**Issue by digivava** [matt-deboer/kuill#12]
When listing resources, there's a bit of unnecessary cognitive work I need to do as a user to remember what each resource kind abbreviation ("De", "Ep", etc.) stands for.  For devs new to Kubernetes I could see this being confusing too, since they haven't internalized the resource kind names yet.

Just using the word "Deployment" or "Endpoint" would be easy and clear

**Comment by matt-deboer** [comment]
Changed to just displaying resource kind names
